# Generated by Django 4.1.2 on 2022-10-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.IntegerField(choices=[(0, 'Weak'), (1, 'Normal'), (2, 'Good')], max_length=1),
        ),
    ]
