# Generated by Django 4.1.2 on 2022-10-31 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydictionary', '0002_alter_videocategory_name_alter_word_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
