# Generated by Django 4.1.2 on 2022-11-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydictionary', '0003_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Weak'), (1, 'Normal'), (2, 'Good')], null=True),
        ),
    ]
