# Generated by Django 4.1.2 on 2022-11-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydictionary', '0004_alter_word_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='words',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
    ]
