# Generated by Django 4.1.2 on 2022-11-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='roomname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
